# Generated by Django 4.1.2 on 2022-11-01 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='name',
            new_name='title',
        ),
    ]
